actualite/urls.py
from django.conf.urls import re_path

from . import views # import views so we can use them in urls.

app_name = "actualite"

urlpatterns = [
    re_path(r'^$', views.actualites, name="articles"), # "/product" will call the method "index" in "views.py"
    re_path(r'^(?P<article_id>[0-9a-f-]+)/$', views.see_more, name="detail"),
]

galerie/urls.py
from django.conf.urls import re_path

from . import views # import views so we can use them in urls.

app_name = "galerie"

urlpatterns = [
    re_path(r'^$', views.photos, name="lesphotos"), # "/product" will call the method "index" in "views.py"
    #re_path(r'^(?P<product_id>[0-9]+)/$', views.detail, name="detail"),
]

renaissance/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.utils.translation import ugettext_lazy as _

from django.conf.urls.static import static
from django.views.generic import TemplateView

from actualite import views
from adhesion import views
from contact_us import views
from galerie import views
from newsletter import views
from titrologie import views
from forum_accounts.views import (login_view, register_view, logout_view)
from .views import home_page

app_name = "renaissance"
admin.site.site_header = _("Rénaissance")
admin.site.site_title = _("Building Craftsmen")

urlpatterns = [
    re_path(r'^$', home_page, name='home'),
    re_path(r'^actualites/', include('actualite.urls', namespace='actualite')),
    re_path(r'^adhesion/', include('adhesion.urls', namespace='adhesion')),
    re_path(r'^contactez-nous/', include('contact_us.urls', namespace='contact_us')),
    re_path(r'^nos-photos/', include('galerie.urls', namespace='galerie')),
    re_path(r'^notifications/', include('newsletter.urls', namespace='newsletter')),
    re_path(r'^revues-de-presse/', include('titrologie.urls', namespace='titrologie')),
    re_path(r'^forum-comments/', include('forum_comments.urls', namespace='comments')),
    re_path(r'^forum/', include('forum_post.urls', namespace='posts')),
    #re_path(r'^login/', login_view, name='login'),
    re_path(r'^jet/', include('jet.urls', 'jet')),
    re_path(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('ad-website/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

actualite/models.py
import os
import uuid
import random

from django.db import models

# Create your models here.
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext

def image_path(instance, filename):
    new_filename = random.randint(1,3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "actualite/{new_filename}/{final_filename}".format(
            new_filename=new_filename,
            final_filename=final_filename)

class Categorie(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Article(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    titre   =  models.CharField(max_length=200)
    image   =  models.ImageField(upload_to=image_path, null=True, blank=True)
    genre   =  models.ForeignKey('Categorie', on_delete=models.CASCADE)
    active  =  models.BooleanField(default=True)
    content =  models.TextField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.titre

class Nouveaute(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    titre   =  models.CharField(max_length=200)
    image   =  models.ImageField(upload_to=image_path, null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titre


class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    post = models.ForeignKey(Article,on_delete=models.CASCADE,related_name='comments')
    nom = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Commenté {} par {}'.format(self.message, self.nom)

actualite/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('nom', 'email', 'message')

actualite/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import transaction, IntegrityError
from django.core.mail import send_mail
from renaissance.settings import EMAIL_HOST_USER
from django.template.loader import render_to_string
from django.utils.html import strip_tags
# Create your views here.
from .models import Article, Categorie, Nouveaute
from titrologie.models import Revue
from .forms import CommentForm


def actualites(request):
    articles = Article.objects.all()
    cartego  = Categorie.objects.all()
    revue = Revue.objects.all()[:5]

    paginator = Paginator(articles, 4)
    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    context = {
        'title': 'Actualité Ivoirienne',
        'articles': articles,
        'category': cartego,
        'revue': revue,
        'paginate': True
    }

    return render(request, 'actualite/listing.html', context)


@transaction.atomic
def see_more(request, article_id):
    template_name = 'actualite/see-more.html'
    article = get_object_or_404(Article, pk=article_id)
    last_art = Article.objects.all()[:3]
    last_news = Nouveaute.objects.all()[:3]
    comments = article.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            nom = comment_form.cleaned_data['nom']
            email = comment_form.cleaned_data['email']
            message = comment_form.cleaned_data['message']
            # Créer un objet Commentaire mais ne pas encore enregistrer dans la base de données
            new_comment = comment_form.save(commit=False)
            # Attribuer le message actuel au commentaire
            new_comment.post = article
            guest_name = new_comment.nom
            guest_email = new_comment.email
            guest_message = new_comment.message
            subject = "Notification sur Actualité"
            print(new_comment.id)
            context = {
                'id': new_comment.id,
                'author': guest_name,
                'message': guest_message,
                'article': article
            }
            msg_html = render_to_string('actualite/email.html', context)
            plain_message = strip_tags(msg_html)
            # Enregistrez le commentaire dans la base de données
            send_mail(subject, plain_message, EMAIL_HOST_USER, ['kouameaugui@gmail.com'], fail_silently = False, html_message=msg_html)
            new_comment.save()
            
    else:
        comment_form = CommentForm()
    return render(request, template_name, {
                'article_id': article.id,
                'article_titre': article.titre,
                'last': last_art,
                'l_new': last_news,
                'content': article.content,
                'type': article.genre,
                'thumbnail': article.image,
                'comments': comments,
                'new_comment': new_comment,
                'comment_form': comment_form
            })

actualite/templates/actualite/email.html
<!DOCTYPE html>
<html  style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
<head>
<meta name="viewport" content="width=device-width" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title></title>
<style type="text/css">
img {
max-width: 100%;
}
body {
-webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; line-height: 1.6em;
}
body {
background-color: #f6f6f6;
}
@media only screen and (max-width: 640px) {
  body {
    padding: 0 !important;
  }
  h1 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h2 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h3 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h4 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h1 {
    font-size: 22px !important;
  }
  h2 {
    font-size: 18px !important;
  }
  h3 {
    font-size: 16px !important;
  }
  .container {
    padding: 0 !important; width: 100% !important;
  }
  .content {
    padding: 0 !important;
  }
  .content-wrap {
    padding: 10px !important;
  }
  .invoice {
    width: 100% !important;
  }
}
</style>
</head>

<body itemscope itemtype="http://schema.org/EmailMessage" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; line-height: 1.6em; background-color: #f6f6f6; margin: 0;" bgcolor="#f6f6f6">

<table class="body-wrap" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; background-color: #f6f6f6; margin: 0;" bgcolor="#f6f6f6"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top"></td>
    <td class="container" width="600" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; display: block !important; max-width: 600px !important; clear: both !important; margin: 0 auto;" valign="top">
      <div class="content" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; max-width: 600px; display: block; margin: 0 auto; padding: 20px;">
        <table class="main" width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; border-radius: 3px; background-color: #fff; margin: 0; border: 1px solid #e9e9e9;" bgcolor="#fff"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="alert alert-warning" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 16px; vertical-align: top; color: #fff; font-weight: 500; text-align: center; border-radius: 3px 3px 0 0; background-color: #123549; margin: 0; padding: 20px;" align="center" bgcolor="#123549" valign="top">
             <b> {{ author }} </b>, a commenté votre article : <b> {{ article }}.</b>
            </td>
          </tr><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-wrap" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 20px;" valign="top">
              <table width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
                    <strong style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">Son avis est le suivant:</strong>
                  </td>
                </tr><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
                    {{ message }}
                  </td>
                </tr><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
                    <a href="http://127.0.0.1:8000/ad-website/actualite/comment/" class="btn-primary" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; color: #FFF; text-decoration: none; line-height: 2em; font-weight: bold; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; text-transform: capitalize; background-color: #4BB543; margin: 0; border-color: #4BB543; border-style: solid; border-width: 10px 20px;">Approuver</a>
                  </td>
                </tr><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
                    <b>RENAISSANCE</b>
                  </td>
                </tr></table></td>
          </tr></table><div class="footer" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; clear: both; color: #999; margin: 0; padding: 20px;">
          <table width="100%" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="aligncenter content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 12px; vertical-align: top; color: #999; text-align: center; margin: 0; padding: 0 0 20px;" align="center" valign="top"><a style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 12px; color: #999; text-decoration: underline; margin: 0;">la côte d'ivoire, nôtre bien commun</a></td>
            </tr></table></div></div>
    </td>
    <td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top"></td>
  </tr></table></body>
</html>

actualite/templates/actualite/list.html
{% include 'nav.html' %}
<br><br>
  <!-- Main layout -->
  <main>
    <div class="container-fluid">
      <!-- Magazine -->
      <div class="row mt-5">
        <!-- Main newsfeed -->
        <div class="col-xl-8 col-lg-8 col-md-12">
        <!--Section: Magazine posts-->
          <section class="section extra-margins listing-section">
            <h5 class="font-weight-bold"><strong>DERNIÈRES NOUVELLES</strong></h5>
            <hr class="red title-hr" style="background:#123549!important">

            <!--Carousel Wrapper-->
            <div id="carousel-example-2" class="carousel slide my-4 z-depth-1" data-ride="carousel">
              <!--Indicators-->
              <ol class="carousel-indicators">
                <li data-target="#carousel-example-2" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-2" data-slide-to="1"></li>
                <li data-target="#carousel-example-2" data-slide-to="2"></li>
              </ol>
              <!--/.Indicators-->
              <!--Slides-->
              <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                  <div class="view">
                    <img class="d-block w-100 rounded" src="http://www.linfodrome.com/media/k2/items/cache/1f3fb3f82022b55c1de6cca51f869f2c_L.jpg"
                      alt="First slide">
                    <div class="mask rgba-black-light"></div>
                  </div>
                  <div class="carousel-caption">
                    <h6 class="h6-responsive font-weight-bold">Journées politiques du Pdci : Le pari de la mobilisation réussie</h6>
                  </div>
                </div>
              <div class="carousel-item">
                  <!--Mask color-->
                <div class="view">
                    <img class="d-block w-100 rounded" src="http://www.linfodrome.com/media/k2/items/cache/7402d787bd0bf5151148d9f0ee5318d2_L.jpg"
                      alt="Second slide">
                    <div class="mask rgba-black-light"></div>
                  </div>
                  <div class="carousel-caption">
                    <h6 class="h6-responsive font-weight-bold">Guillaume Soro annonce son retour en Côte d'Ivoire pour la semaine prochaine et craint pour la stabilité du pays</h6>
                  </div>
                </div>
              <div class="carousel-item">
                  <!--Mask color-->
                <div class="view rgba-black-slight">
                    <img class="d-block w-100 rounded" src="http://www.linfodrome.com/media/k2/items/cache/ff922efc378d3c92c3da204fe68be8fb_L.jpg"
                      alt="Third slide">
                    <div class="mask rgba-black-light"></div>
                  </div>
                  <div class="carousel-caption">
                    <h6 class="h6-responsive font-weight-bold">Affaire ''taupes de Soro au Rhdp'': Ouattara confie une mission urgente à ''Photocopie'', ce qui se prépare contre des cadres du Rhdp</h6>
                  </div>
                </div>
              </div>
              <!--/.Slides-->
              <!--Controls-->
              <a class="carousel-control-prev" href="#carousel-example-2" role="button" data-slide="prev">
                <i class="fas fa-chevron-left"></i>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carousel-example-2" role="button" data-slide="next">
                <i class="fas fa-chevron-right"></i>
                <span class="sr-only">Next</span>
              </a>
              <!--/.Controls-->
            </div>
            <!--/.Carousel Wrapper-->

          

          <!-- Section: News -->
          <section>
            <h5 class="dark-grey-text text-uppercase font-weight-bold">
              <strong>{{ list_title }}</strong>
            </h5>
            <hr style="background:#123549 !important">
          {% if articles|length_is:"0" %}
            <h1>coucou</h1>
          {% else %}
            <!-- Grid row -->
            <div class="row">
              {% for product in articles %}
                <!-- Grid column -->
                <div class="col-md-12 mb-4">
                  <!--News card-->
                  <div class="card  mb-3 text-center hoverable">
                    <div class="card-body">
                      <!--Grid row-->
                      <div class="row">
                        <!--Grid column-->
                        <div class="col-md-5 mx-3 my-3">
                          <!--Featured image-->
                          
                          <div class="view overlay rgba-white-slight">
                            {% if product.image %}
                                <img src="{{ product.image.url }}" class="img-fluid rounded-bottom" alt="{{ product.titre }}">
                              {% else %}
                                {% load static %}
                                <img src="{% static 'renaissance/img/earth-globe.jpg' %}" class="img-fluid rounded-bottom" alt="{{ product.titre }}">
                            {% endif %}
                            <a>
                              <div class="mask"></div>
                            </a>
                          </div>
                        </div>
                        <!--Grid column-->

                        <!--Grid column-->
                        <div class="col-md-6 text-left ml-xl-3 ml-lg-0 ml-md-3 mt-3">
                          <h6 class="mb-4">
                            <strong style="color:#123549 !important">{{ product.titre }}</strong>
                          </h6>
                          <p class="dark-grey-text" style="text-align: justify;text-justify: inherit;">{{ product.content|slice:"0:150" }}...</p>
                          <p><a><strong style="color:#123549 !important">{{ product.genre }}</strong></a></p>
                          <a class="btn btn-indigo btn-sm" style="background:#123549 !important" href="{% url 'actualite:detail' article_id=product.id %}">Voir</a>
                        </div>
                        <!--Grid column-->
                      </div>
                      <!--Grid row-->
                    </div>
                  </div>
                  <!--News card-->
                </div>
                <!-- Grid column -->
              {% endfor %}
            </div>
            <!-- Grid row -->
            {% if paginate %}
              <!--Pagination dark-->
              <nav>
                <ul class="pagination pg-dark justify-content-center">
                  <!--Arrow left-->
                  {% if articles.has_previous %}
                    <li class="page-item">
                      <a class="page-link" aria-label="Previous" href="?page={{ articles.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                      </a>
                    </li>
                  {% endif %}
                  <!--Numbers-->
                  {% for i in articles.paginator.page_range %}
                    {% if articles.number == i %}
                      <li class="page-item active">
                        <a class="page-link" style="background:#123549 !important">{{ i }}</a>
                      </li>
                    {% else %}
                      <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                      </li>
                    {% endif %}
                  {% endfor %}

                  <!--Arrow right-->
                  {% if articles.has_next %}
                    <li class="page-item">
                      <a class="page-link" aria-label="Next" href="?page={{ articles.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                      </a>
                    </li>
                  {% endif %}
                </ul>
              </nav>
              <!--/Pagination dark-->
            {% endif %}
          {% endif %}
          </section>
          <!-- Section: News -->
        </div>
        <!-- Main newsfeed -->

        <!-- Sidebar -->
        <div class="col-xl-4 col-lg-4 col-md-12 mt-0 mb-2">
            <section class="section">
                <h5 class="dark-grey-text font-weight-bold">
                    <strong>CATÉGORIES</strong>
                </h5>
                <hr style="background:#123549 !important">
                <ul class="list-group z-depth-1">
                    {% for cat in category %}
                    <li class="list-group-item d-flex text-lowercase justify-content-between align-items-center">
                    <a>{{ cat.name }}</a>
                    <span class="badge indigo badge-pill" style="background:#123549 !important">4</span>
                    </li>
                    {% endfor %}
                </ul>
            </section>

            <!--News Events-->
            <section class="section widget-content mt-5 my-5">
                <div class="card blue-grey lighten-5 card-body pb-0">
                    <div class="single-post">
                        <p class="font-weight-bold dark-grey-text text-center spacing grey lighten-4 py-2 mb-4">
                            <strong>&nbsp;Bulletin d'information&nbsp;</strong>
                        </p>
                        <div class="row mb-4">
                            <div class="col-md-12">

                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!--News events-->

          <h4 class="font-weight-bold"><strong>REVUE DE PRESSE</strong></h4>
          <hr class="red title-hr mb-4"  style="background:#123549!important">
          <section class="section mt-5">
              <div class="row">
                <div class="col-md-10 col-lg-12 mx-auto">
                  <div id="carousel-example-2" class="carousel slide carousel-fade carousel-img" data-ride="carousel">
                    <!--Slides-->
                    <div class="carousel-inner" role="listbox">
                      {% for journal in revue %}
                        {% if forloop.first %}
                        <div class="carousel-item active">
                         {% else %}
                        <div class="carousel-item">
                          {% endif %}
                          <div class="view">
                            {% if journal.image %}
                              <img class="d-block w-100" src="{{ journal.image.url }}" alt="{{ journal.maison }}">
                            {% endif %}
                            <div class="mask rgba-black-light"></div>
                          </div>
                          <div class="carousel-caption">
                            <h3 class="h3-responsive font-weight-bold">{{ journal.maison }}</h3>
                            <p>N° {{ journal.numero }}</p>
                          </div>
                        </div>  
                      {% endfor %} 
                    </div>
                  </div>
                </div>
            </div>
          </section>
        </div>
        <!-- Sidebar -->
      </div>
      <!-- Magazine -->
    </div>
  </main>
  <!-- Main layout -->

actualite/templates/actualite/listing.html
{% extends 'base.html' %}

{% block head_title %}
{{ title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}

    {% include 'actualite/list.html' with list_title='DERNIÈRES NOUVELLES' %}

{% endblock %}