actualite/urls.py
from django.conf.urls import re_path

from . import views # import views so we can use them in urls.

app_name = "actualite"

urlpatterns = [
    re_path(r'^$', views.actualites, name="articles"), # "/product" will call the method "index" in "views.py"
    re_path(r'^(?P<article_id>[0-9a-f-]+)/$', views.see_more, name="detail"),
]

adhesion/urls.py
from django.conf.urls import re_path

from . import views # import views so we can use them in urls.

app_name = "adhesion"

urlpatterns = [
    re_path(r'^$', views.addUser, name="adherant"), # "/product" will call the method "index" in "views.py"
    #re_path(r'^(?P<product_id>[0-9]+)/$', views.detail, name="detail"),
]

contact_us/urls.py
from django.conf.urls import re_path

from . import views # import views so we can use them in urls.

app_name = "contact_us"

urlpatterns = [
    re_path(r'^$', views.contactUs, name="contact"), # "/product" will call the method "index" in "views.py"
    #re_path(r'^(?P<product_id>[0-9]+)/$', views.detail, name="detail"),
]

forum_post/urls.py
from django.conf.urls import re_path
from django.contrib import admin

from .views import poster_auth, poster_reg, post_list, post_create, post_detail, post_update, post_delete

app_name = "posts"

urlpatterns = [
	re_path(r'^$', post_list, name='list'),
	re_path(r'^create/$', post_create, name='create'),
    re_path(r'^je-me-connecte/$', poster_auth, name='authentification'),
    re_path(r'^je-m-inscris/$', poster_reg, name="registration"),
    re_path(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    re_path(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    re_path(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name="delete"),
]

galerie/urls.py
from django.conf.urls import re_path

from . import views # import views so we can use them in urls.

app_name = "galerie"

urlpatterns = [
    re_path(r'^$', views.photos, name="lesphotos"), # "/product" will call the method "index" in "views.py"
    #re_path(r'^(?P<product_id>[0-9]+)/$', views.detail, name="detail"),
]

renaissance/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.utils.translation import ugettext_lazy as _

from django.conf.urls.static import static
from django.views.generic import TemplateView

from actualite import views
from adhesion import views
from contact_us import views
from galerie import views
from newsletter import views
from titrologie import views
from forum_accounts.views import (login_view, register_view, logout_view)
from .views import home_page

app_name = "renaissance"
admin.site.site_header = _("Rénaissance")
admin.site.site_title = _("Building Craftsmen")

urlpatterns = [
    re_path(r'^$', home_page, name='home'),
    re_path(r'^actualites/', include('actualite.urls', namespace='actualite')),
    re_path(r'^adhesion/', include('adhesion.urls', namespace='adhesion')),
    re_path(r'^contactez-nous/', include('contact_us.urls', namespace='contact_us')),
    re_path(r'^nos-photos/', include('galerie.urls', namespace='galerie')),
    re_path(r'^notifications/', include('newsletter.urls', namespace='newsletter')),
    re_path(r'^revues-de-presse/', include('titrologie.urls', namespace='titrologie')),
    re_path(r'^forum-comments/', include('forum_comments.urls', namespace='comments')),
    re_path(r'^forum/', include('forum_post.urls', namespace='posts')),
    #re_path(r'^login/', login_view, name='login'),
    re_path(r'^jet/', include('jet.urls', 'jet')),
    re_path(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('ad-website/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}Rénaissance Portail web{% endblock head_title %}</title>
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'renaissance/img/logo.jpeg' %}" />
    <link href="{% static 'renaissance/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'renaissance/css/mdb.min.css' %}" type="text/css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <style type="text/css">
        html,
        body,
        header,
        .jarallax {
            height: 600px;
        }
        
        @media (max-width: 740px) {
            html,
            body,
            header,
            .jarallax {
                height: 100%;
            }
        }
        
        @media (min-width: 800px) and (max-width: 850px) {
            html,
            body,
            header,
            .jarallax {
                height: 100%;
            }
        }
        .gallery {
-webkit-column-count: 3;
-moz-column-count: 3;
column-count: 3;
-webkit-column-width: 33%;
-moz-column-width: 33%;
column-width: 33%; }
.gallery .pics {
-webkit-transition: all 350ms ease;
transition: all 350ms ease; }
.gallery .animation {
-webkit-transform: scale(1);
-ms-transform: scale(1);
transform: scale(1); }

@media (max-width: 450px) {
.gallery {
-webkit-column-count: 1;
-moz-column-count: 1;
column-count: 1;
-webkit-column-width: 100%;
-moz-column-width: 100%;
column-width: 100%;
}
}

@media (max-width: 400px) {
.btn.filter {
padding-left: 1.1rem;
padding-right: 1.1rem;
}
}
    </style>
</head>

<body class="homepage-v1 hidden-sn animated">


    <div class="">
        {% block content %}{% endblock %}
    </div>

    <footer class="page-footer stylish-color text-center text-md-left  pt-4" style="background: #123549 !important;">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h6 class="text-uppercase font-weight-bold">A Propos</h6>
                    <hr>
                    <p>Nous somme un mouvement politique transpartisan. De ce fait il est ouvert à toute personne, à toute organisation qui adhère à sa vision et ses valeurs sont donc le principal centre d’intérêt reste la Reconstruction de la Côte d’Ivoire
                        et le bien-être de la population ivoirienne.</p>
                </div>

                <hr class="w-50 clearfix d-md-none" style="background:#fff">

                <div class="col-md-3">
                    <h6 class="text-uppercase font-weight-bold">Liens Utils</h6>
                    <hr>
                    <ul class="list-unstyled">
                        <li>
                            <a href="{% url "adhesion:adherant" %}">
                                <p>Devenez membre</p>
                            </a>
                        </li>
                        <li>
                            <a href="#!">
                                <p>Souscrire au bulletin d'information</p>
                            </a>
                        </li>
                        <li>
                            <a href="#!">
                                <p>Rénaissance sur les réseaux sociaux</p>
                            </a>
                        </li>
                    </ul>
                </div>

                <hr class="w-50 clearfix d-md-none" style="background:#fff">

                <div class="col-md-3">
                    <h6 class="text-uppercase font-weight-bold">Contactez Nous</h6>
                    <hr>
                    <ul class="list-unstyled">
                        <li>
                            <p><i class="fa fa-home mr-3"></i>94550 Franklin Roosevelt, Chevilly Larue, Paris, FRANCE.</p>
                        </li>
                        <li>
                            <p><i class="fa fa-envelope mr-3"></i>infos@renaissance.com</p>
                        </li>
                        <li>
                            <p><i class="fa fa-phone mr-3"></i> 07 68 18 28 22</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row py-3 d-flex align-items-center">
                <div class="col-md-7 col-lg-8">
                    <p class="text-center text-md-left grey-text">&copy; 2020 <a href="" target="_blank"> Rénaissance.com </a></p>
                </div>
                <div class="col-md-5 col-lg-4 ml-lg-0">
                    <div class="social-section text-center text-md-left">
                        <ul class="list-unstyled list-inline">
                            <li class="list-inline-item mx-0"><a class="btn-floating btn-sm rgba-white-slight mr-xl-4" style="color:#ffffff!important;"><i class="fab fa-facebook-f"></i></a></li>
                            <li class="list-inline-item mx-0"><a class="btn-floating btn-sm rgba-white-slight mr-xl-4" style="color:#ffffff!important;"><i class="fab fa-twitter"></i></a></li>
                            <li class="list-inline-item mx-0"><a class="btn-floating btn-sm rgba-white-slight mr-xl-4" style="color:#ffffff!important;"><i class="fab fa-linkedin-in"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script type="text/javascript" src="{% static 'renaissance/js/jquery-3.4.0.min.js' %}"></script>
    <script type="text/javascript">
     $(function() {
        var selectedClass = "";
        $(".filter").click(function(){
        selectedClass = $(this).attr("data-rel");
        $("#gallery").fadeTo(100, 0.1);
        $("#gallery div").not("."+selectedClass).fadeOut().removeClass('animation');
        setTimeout(function() {
        $("."+selectedClass).fadeIn().addClass('animation');
        $("#gallery").fadeTo(300, 1);
        }, 300);
        });
     });
    </script>
    <script type="text/javascript" src="{% static 'renaissance/js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'renaissance/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'renaissance/js/mdb.min.js' %}"></script>
</body>

</html>

templates/comment_thread.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}
{{ object }}

{% include 'nav.html' %}
<br>
<main class="">
    <div class="container">
         <nav class="navbar navbar-expand-lg navbar-dark  mt-5" style="background-color: #123549 !important;">
        <a class="font-weight-bold white-text mr-4" href="{% url "posts:list" %}">Accueil Form</a>
        
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1" aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent1">
                    <ul class="navbar-nav mr-auto">
                        <div class="modal fade" id="orangeModalSubscription" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-notify modal-warning" role="document">
                                <div class="modal-content">
                                    <div class="modal-header text-center" style="background: #123549 !important">
                                        <h4 class="modal-title white-text w-100 font-weight-bold py-2">Verification</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true" class="white-text">&times;</span>
                                    </button>
                                </div>

                                <!--Body-->
                                <div class="modal-body">
                                    <div class="md-form">
                                        <p>
                                            Viellez choisir l'action à éffectuer !
                                        </p>
                                    </div>
                                </div>

                                <!--Footer-->
                                <div class="modal-footer justify-content-center">
                                    <a type="button" href="{% url 'posts:registration' %}" class="btn btn-success">Je m'inscris <i class="far fa-gem ml-1 text-white"></i></a>
                                    <a type="button" href="{% url 'posts:authentification' %}" class="btn btn-outline-grey waves-effect" style="color: #123549 !important">Je me connecte <i class="fas fa-paper-plane-o ml-1"></i></a>
                                </div>
                                </div>
                                <!--/.Content-->
                            </div>
                        </div>
                        </ul>
                        <!-- Links -->

                        <!-- Search form -->
                        <form class="search-form" role="search">
                            <div class="form-group md-form my-0 waves-light">
                                <input type="text" class="form-control" placeholder="Rechercher">
                            </div>
                        </form>
                    </div>
                </nav>
        <div class="row">
            <!-- Content -->
            <div class="col-lg-8">
                <section class="section pt-4">
                    <div class="row pt-1">
                        <div class="col-lg-12">
                            <section class="section my-5">
                                <blockquote class="note note-light">
                                    <p>{{ comment.content }}</p>
                                    <footer>Répondu par {{ comment.user }} -- il y a {{ comment.timestamp|timesince }}  | {% if comment.children.count > 0 %}{{ comment.children.count }} Réponse{% if comment.children.count > 1 %}s{% endif %} {% endif %} {% if request.user == comment.user %}<a href='{{ comment.get_delete_url }}'> | Supprimer</a> {% endif %}</footer>
                                </blockquote>
                                <hr/>
                                <div class="p-3">
                                    {% for child_comment in comment.children %}
                                    <blockquote class="note note-info">
                                        <p>{{ child_comment.content }}</p>
                                        <footer>Répondu par {{ child_comment.user }} -- il y a {{ child_comment.timestamp|timesince }}  | {% if request.user == child_comment.user %}<a href='{{ child_comment.get_delete_url }}'> Supprimer</a>{% endif %}</footer>
                                    </blockquote>
                                    {% endfor %}
                                    {% if request.user.is_authenticated %}
                                    <form method="POST" action="."> {% csrf_token %}
                                        {{ form|crispy }}
                                        <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                                        <input type='submit' style="background: #123549 !important;" value='Répondre' class='btn btn-default'>
                                    </form>
                                    {% else %}
                                    <p>Vous devez être connecté pour répondre à ce commentaire </p>
                                    {% endif %}
                                </div>
                                <hr/>
                            </section>
                        </div>
                    </div>
                </section>
            </div>
            <!--Sidebar-->
            <div class="col-lg-4 col-12 pt-4 my-5">
                <!--Card-->
                <div class="card mb-4">
                    <!-- Card header -->
                    <div class="card-header text-center"><strong>Les règles à respecter</strong></div>
                    <!--Card content-->
                    <div class="card-body">
                        <ul class="list-unstyled">
                            <li>
                                <span> - Rédiger les messages dans un langage clair sans abréviations.</span>
                            </li>
                            <li>
                                <span> - Faire usage de formule de politesse et échanger avec courtoisie.</span>
                            </li>

                            <li>
                                <span> - Réserver un accueil cordial aux nouveaux utilisateurs.</span>
                            </li>
                             <li>
                                <span> - Poster son message dans le thème le plus approprié.</span>
                            </li>
                             <li>
                                <span> - Respecter la législation en vigueur.</span>
                            </li>
                        </ul>
                        <p class="text-danger"><i class="fas fa-ban"></i> <em>Attention, toutes publications ne respectant pas l'une des règles ci-dessus sera immédiatement supprimer</em></p>
                    </div>
                </div>
                <!--/.Card-->
            </div>
            <!--Sidebar-->
        </div>
    </div>
</main>

{% endblock content %}

templates/confirm_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}
{% include 'nav.html' %}

<main>
    <div class="container my-5 py-5 z-depth-1 p-2">

 
    <!--Section: Content-->
    <section class="text-center px-md-5 mx-md-5 dark-grey-text">

      <h3 class="font-weight-bold">Confirmation de la suppression </h3>
        
      
            <form method="POST" action="."> {% csrf_token %}
                <p>Etes-vous sûr de vouloir supprimer cette réponse: " <strong>{{ object.content }}</strong> "?</p>
              
                <input type='submit' value='OUI' class='btn btn-success'>
                <a href='{{ object.get_absolute_url }}' class='btn btn-danger'>NON</a>
            </form>


    </section>
    <!--Section: Content-->


  </div>
</main>
{% endblock content %}

templates/home_page.html
{% extends 'base.html' %}


{% block content %}

  {% include 'main.html' %}

{% endblock %}

templates/nav.html
<nav class="navbar  navbar-expand-lg fixed-top  navbar-dark scrolling-navbar white" style="background-color: #123549 !important;">
        <div class="container">
            <a class="navbar-brand" style="padding-right: 5%;" target="_blank">{% load static %}<img src="{% static 'renaissance/img/logo.jpeg' %}" style="width:200px; height: 70px;float: left;" alt="Logo"></a>  
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navSupport" aria-controls="navSupport" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

            <div class="collapse navbar-collapse" id="navSupport">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link waves-effect waves-light dark-grey-text font-weight-bold" href="{% url 'home' %}" style="color:#ffffff!important;"> ACCUEIL</a><span class="sr-only">(current)</span></li>
                    <li class="nav-item"><a class="nav-link waves-effect waves-light dark-grey-text font-weight-bold" href="{% url 'actualite:articles' %}" style="color:#ffffff!important;">ACTUALITÉS</a></li>
                    <li class="nav-item"><a class="nav-link waves-effect waves-light dark-grey-text font-weight-bold" href="{% url 'titrologie:revue' %}" style="color:#ffffff!important;">TITROLOGIE</a></li>
                    <li class="nav-item"><a class="nav-link waves-effect waves-light dark-grey-text font-weight-bold" style="color:#ffffff!important;" href="{% url "galerie:lesphotos" %}">GALÉRIE</a></li>
                    <li class="nav-item"><a class="nav-link waves-effect waves-light dark-grey-text font-weight-bold" style="color:#ffffff!important;" href="{% url "contact_us:contact" %}">CONTACT</a></li>
                    <li class="nav-item"><a class="nav-link waves-effect waves-light dark-grey-text font-weight-bold" style="color:#ffffff!important;" href="{% url "posts:list" %}">FORUM</a></li>
                </ul>
            </div>
        </div>
</nav>

templates/post_list.html
{% extends 'base.html' %}

{% block head_title %}
{{ title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}  
{% include 'nav.html' %}
<main>
<!-- Main Container -->
<div class="container mt-2 pt-2">
    <nav class="navbar navbar-expand-lg navbar-dark  mt-5" style="background-color: #123549 !important;">
        <a class="font-weight-bold white-text mr-4" href="{% url "posts:list" %}">Accueil Forum</a>
        {% block post_detail_link %}
        {% endblock %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1" aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent1">
                    <ul class="navbar-nav mr-auto">
                        <div class="modal fade" id="orangeModalSubscription" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-notify modal-warning" role="document">
                                <div class="modal-content">
                                    <div class="modal-header text-center" style="background: #123549 !important">
                                        <h4 class="modal-title white-text w-100 font-weight-bold py-2">Viellez choisir l'action à éffectuer</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true" class="white-text">&times;</span>
                                    </button>
                                </div>
        

                                <!--Footer-->
                                <div class="modal-footer justify-content-center">
                                    <a type="button" href="{% url 'posts:registration' %}" class="btn btn-success">Je m'inscris <i class="far fa-gem ml-1 text-white"></i></a>
                                    <a type="button" href="{% url 'posts:authentification' %}" class="btn btn-outline-grey waves-effect" style="color: #123549 !important">Je me connecte <i class="fas fa-paper-plane-o ml-1"></i></a>
                                </div>
                                </div>
                                <!--/.Content-->
                            </div>
                        </div>
                        <li class="nav-item">
                            {% if check_user.is_authenticated %}
                                <a href="{% url 'posts:create' %}" class="nav-link border border-light rounded waves-effect mr-2">
                            {% else %}
                                <a data-toggle="modal" data-target="#orangeModalSubscription" class="nav-link border border-light rounded waves-effect mr-2">
                            {% endif %}
                                <i class="fas fa-pencil-alt mr-1"></i>Posez votre question
                            </a>
                        </li>
                        </ul>
                        <!-- Links -->

                        <!-- Search form -->
                        <form class="search-form" role="search">
                            <div class="form-group md-form my-0 waves-light">
                                <input type="text" class="form-control" placeholder="Rechercher" name='q' value='{{ request.GET.q }}'>
                            </div>
                        </form>
                    </div>
                </nav>
        <div class="row">
            <!-- Content -->
            <div class="col-lg-8">
                <section class="section pt-4">
                    <div class="row pt-1">
                        <div class="col-lg-12">
                            {% if check_user.is_authenticated %}
                            <h4 class="text-center">Connecter en tant que : <strong class="text-uppercase font-weight-bold">{{ user }}</strong></h4>
                            {% else %}
                            <h4 class="text-center">Vous n'êtes pas connecté, mais vous pouvez lire toute nos questions</h4>
                            {% endif %}
                            <section class="section my-5">
                             {% if object_list|length_is:"0" %}
                                <h1>Désolé, il n'y a aucun sujet pour l'instant</h1>
                            {% else %}
                            {% for obj in object_list %}
                                <div class="question-card card mb-4">
                                    <!-- Card header -->
                                    {% if obj.draft %}<h3>Staff only: Draft</h3>{% endif %} {% if obj.publish > today %}<h3>Staff Only: Future Post</h3>{% endif %}
                                    <div class="card-header forum-card-img-30 d-flex justify-content-between">
                                        <p class="pt-2 mb-0">
                                            <img src="https://secure.gravatar.com/avatar/62c9c125499e280d7f96a75e939f3046?s=96&d=mm&r=g" alt="" class="rounded-circle mr-2">
                                            {% if obj.user %}
                                            <strong class="text-uppercase">
                                                {{ obj.user }},
                                            </strong>
                                            {% endif %}
                                            Publier le {{ obj.publish }}
                                        </p>
                                    </div>
                                    <!--Card content-->
                                    <div class="card-body text-center">
                                     <a href="{{ obj.get_absolute_url }}" style="text-decoration:none; color:#123549 !important;font-weight:bold">{{ obj.title }}</a>
                                    </div>
                                </div>
                            {% endfor %}
                            {% if paginate %}
                                <!--Pagination dark-->
                                <nav>
                                    <ul class="pagination pg-dark justify-content-center">
                                    <!--Arrow left-->
                                    {% if object_list.has_previous %}
                                        <li class="page-item">
                                        <a class="page-link" aria-label="Previous" href="?page={{ object_list.previous_page_number }}">
                                            <span aria-hidden="true">&laquo;</span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                        </li>
                                    {% endif %}
                                    <!--Numbers-->
                                    {% for i in object_list.paginator.page_range %}
                                        {% if object_list.number == i %}
                                        <li class="page-item active">
                                            <a class="page-link" style="background:#123549 !important">{{ i }}</a>
                                        </li>
                                        {% else %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                        </li>
                                        {% endif %}
                                    {% endfor %}

                                    <!--Arrow right-->
                                    {% if object_list.has_next %}
                                        <li class="page-item">
                                        <a class="page-link" aria-label="Next" href="?page={{ object_list.next_page_number }}">
                                            <span aria-hidden="true">&raquo;</span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                        </li>
                                    {% endif %}
                                    </ul>
                                </nav>
                                <!--/Pagination dark-->
                                {% endif %}
                                {% endif %}
                            </section>
                        </div>
                    </div>
                </section>
            </div>
            <!--Sidebar-->
            <div class="col-lg-4 col-12 pt-4 my-5">
                <!--Card-->
                <div class="card mb-4">
                    <!-- Card header -->
                    <div class="card-header text-center"><strong>Les règles à respecter</strong></div>
                    <!--Card content-->
                    <div class="card-body">
                        <ul class="list-unstyled">
                            <li>
                                <span> - Rédiger les messages dans un langage clair sans abréviations.</span>
                            </li>
                            <li>
                                <span> - Faire usage de formule de politesse et échanger avec courtoisie.</span>
                            </li>

                            <li>
                                <span> - Réserver un accueil cordial aux nouveaux utilisateurs.</span>
                            </li>
                             <li>
                                <span> - Poster son message dans le thème le plus approprié.</span>
                            </li>
                             <li>
                                <span> - Respecter la législation en vigueur.</span>
                            </li>
                        </ul>
                        <p class="text-danger"><i class="fas fa-ban"></i> <em>Attention, toutes publications ne respectant pas l'une des règles ci-dessus sera immédiatement supprimer</em></p>
                    </div>
                </div>
                <!--/.Card-->
            </div>
            <!--Sidebar-->
        </div>
    </div>
</main>
<br>
<br>
<br>
{% endblock %}